In [ ]:
import pickle   # importing pickle for saving and loading machine learning models
import pandas as pd  # importing pandas for analyzing, cleaning, exploring, and manipulating data
from sklearn.model_selection import train_test_split  # importing train_test_split for spliting the data
from imblearn.over_sampling import SMOTE  # importing SMOTE for Balancing the Data

In [ ]:
df=pd.read_csv("/content/loan_approved (1).csv")  # Loading dataset

In [ ]:
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status (Approved)
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [ ]:
df.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area',
       'Loan_Status (Approved)'],
      dtype='object')

In [ ]:
df.isnull().sum()

Loan_ID                    0
Gender                    13
Married                    3
Dependents                15
Education                  0
Self_Employed             32
ApplicantIncome            0
CoapplicantIncome          0
LoanAmount                22
Loan_Amount_Term          14
Credit_History            50
Property_Area              0
Loan_Status (Approved)     0
dtype: int64

In [ ]:
df.loc[df['Gender'].isnull(),'Gender']="Male"  # Filling null value using Most_Frequent Elements of Gender column.

In [ ]:
df.loc[df['Married'].isnull(),'Married']="Yes"    # Filling null value using Most_Frequent Elements of Married column.

In [ ]:
df.loc[df['Dependents'].isnull(),'Dependents']='0'   # Filling null value using Most_Frequent Elements of Dependents

In [ ]:
df.loc[df['Self_Employed'].isnull(),'Self_Employed']='No'   # Filling null value using Most_Frequent Elements of Self_Employed

In [ ]:
#  Filling null values using Median of LoanAmount
df.loc[df['LoanAmount'].isnull(),'LoanAmount']=df['LoanAmount'].median()

In [ ]:
#  Filling null values using Most_Frequent value of Loan_Amount_Term column
df.loc[df['Loan_Amount_Term'].isnull(),'Loan_Amount_Term']=360.0

In [ ]:
df.loc[df['Credit_History'].isnull(),'Credit_History']=0.0    # Filling null values of Credit_History

In [ ]:
df.isnull().sum()   # Checking null values are available or not

Loan_ID                   0
Gender                    0
Married                   0
Dependents                0
Education                 0
Self_Employed             0
ApplicantIncome           0
CoapplicantIncome         0
LoanAmount                0
Loan_Amount_Term          0
Credit_History            0
Property_Area             0
Loan_Status (Approved)    0
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

class ModifiedLabelEncoder(LabelEncoder):
    def fit_transform(self, y, *args, **kwargs):
        return super().fit_transform(y).reshape(-1, 1)

    def transform(self, y, *args, **kwargs):
        return super().transform(y).reshape(-1, 1)

In [ ]:
def divide_by_12(x):
    return x / 12

def same(x):
    return x

In [ ]:
# Load a preprocessor object from a pickled file
with open("/content/svmpreprocesspickle.pkl","rb") as f:
  preprocessor=pickle.load(f)

In [ ]:
preprocessor  # Preprocessor or PipeLine

ColumnTransformer(transformers=[('OHE columns', OneHotEncoder(),
                                 ['Self_Employed', 'Property_Area', 'Gender']),
                                ('Label_encoder', ModifiedLabelEncoder(),
                                 'Married'),
                                ('standard_scaler', StandardScaler(),
                                 ['ApplicantIncome', 'CoapplicantIncome',
                                  'LoanAmount']),
                                ('custom',
                                 FunctionTransformer(func=<function divide_by_12 at 0x7c426d5b02c0>),
                                 ['Loan_Amount_Term']),
                                ('pass through',
                                 FunctionTransformer(func=<function same at 0x7c426d5b2980>),
                                 ['Credit_History']),
                                ('ordinal dependents',
                                 OrdinalEncoder(categories=[['0', '1', '2',
                                                             '3+']]),
                                 ['Dependents']),
                                ('ordinal education',
                                 OrdinalEncoder(categories=[['Not Graduate',
                                                             'Graduate']]),
                                 ['Education']),
                                ('Label Label encoder', ModifiedLabelEncoder(),
                                 ['Loan_Status (Approved)'])])

In [ ]:
# Spliting the data into train and test
train,test,_,_=train_test_split(df,df['LoanAmount'],test_size=0.2)

In [ ]:
train['Loan_Status (Approved)'].value_counts()  # Checking count of unique values of Loan_Status (Approved) columns

Loan_Status (Approved)
Y    334
N    157
Name: count, dtype: int64

In [ ]:
#Transforming the data

train

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status (Approved)
362,LP002175,Male,Yes,0,Graduate,No,4750,2333.0,130.0,360.0,1.0,Urban,Y
467,LP002501,Male,Yes,0,Graduate,No,16692,0.0,110.0,360.0,1.0,Semiurban,Y
410,LP002318,Female,No,1,Not Graduate,Yes,3867,0.0,62.0,360.0,1.0,Semiurban,N
334,LP002103,Male,Yes,1,Graduate,Yes,9833,1833.0,182.0,180.0,1.0,Urban,Y
363,LP002178,Male,Yes,0,Graduate,No,3013,3033.0,95.0,300.0,0.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,LP001259,Male,Yes,1,Graduate,Yes,1000,3022.0,110.0,360.0,1.0,Urban,N
552,LP002785,Male,Yes,1,Graduate,No,3333,3250.0,158.0,360.0,1.0,Urban,Y
335,LP002106,Male,Yes,0,Graduate,Yes,5503,4490.0,70.0,360.0,1.0,Semiurban,Y
575,LP002868,Male,Yes,2,Graduate,No,3159,461.0,108.0,84.0,1.0,Urban,Y
555,LP002792,Male,Yes,1,Graduate,No,5468,1032.0,26.0,360.0,1.0,Semiurban,Y

In [ ]:
# Transform the training data using the preprocessor object or PipeLine
processed_data=preprocessor.fit_transform(train)

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
processed_data

array([[1., 0., 0., ..., 0., 1., 1.],
       [1., 0., 0., ..., 0., 1., 1.],
       [0., 1., 0., ..., 1., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 1., 1.],
       [1., 0., 0., ..., 2., 1., 1.],
       [1., 0., 0., ..., 1., 1., 1.]])

In [ ]:
# Extract the features (all columns except the last one) from the processed data
x_train=processed_data[:,:-1]

In [ ]:
# Extract the target variable (last column) from the processed data
y_train=processed_data[:,-1] # Last column is target

In [ ]:
y_train

array([1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 1., 0., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 0., 1.,
       1., 1., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1.,
       1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1.,
       0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0.,
       1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1.,
       1., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 0.,
       1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 0., 1.,
       0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 0.,
       1., 1., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 1., 1., 0.,
       1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1.,
       1., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1.,
       1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0.,
       1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 1., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1.])

In [ ]:
## SMOTE


smote=SMOTE()

In [ ]:
x_train_smote,y_train_smote=smote.fit_resample(x_train,y_train)

In [ ]:
a=pd.DataFrame(x_train_smote)
a

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,1.000000,0.000000,0.000000,0.000000,1.0,0.000000,1.000000,1.000000,-0.121375,0.226910,-0.205390,30.0,1.000000,0.000000,1.0
1,1.000000,0.000000,0.000000,1.000000,0.0,0.000000,1.000000,1.000000,1.678185,-0.514728,-0.434144,30.0,1.000000,0.000000,1.0
2,0.000000,1.000000,0.000000,1.000000,0.0,1.000000,0.000000,0.000000,-0.254436,-0.514728,-0.983154,30.0,1.000000,1.000000,0.0
3,0.000000,1.000000,0.000000,0.000000,1.0,0.000000,1.000000,1.000000,0.644591,0.067964,0.389372,15.0,1.000000,1.000000,1.0
4,1.000000,0.000000,0.000000,0.000000,1.0,0.000000,1.000000,1.000000,-0.383126,0.449433,-0.605710,25.0,0.000000,0.000000,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
663,1.000000,0.000000,0.000000,0.000000,1.0,1.000000,0.000000,0.513540,-0.539928,-0.207656,0.178858,30.0,1.000000,1.513540,1.0
664,1.000000,0.000000,0.000000,0.000000,1.0,0.000000,1.000000,1.000000,-0.456638,-0.078159,-0.533814,30.0,0.000000,0.128583,1.0
665,1.000000,0.000000,0.000000,1.000000,0.0,0.255585,0.744415,0.000000,-0.309515,-0.514728,-0.641924,30.0,0.000000,0.000000,1.0
666,0.870608,0.129392,1.000000,0.000000,0.0,0.000000,1.000000,0.129392,0.479754,0.843484,1.931160,30.0,0.870608,0.129392,1.0
667,0.818343,0.181657,0.818343,0.181657,0.0,1.000000,0.000000,0.000000,-0.163304,-0.514728,-0.805315,30.0,1.000000,1.000000,0.0

In [ ]:
len(y_train)  # Checking length of actual y_train

491

In [ ]:
len(y_train_smote)   # Checking length of y_train after apply Smote

668

In [ ]:
from sklearn.svm import SVC  # # assign Support vector classifier
svclassifier = SVC() ## base model with default parameters
svclassifier.fit(x_train_smote,y_train_smote)  ## Fit the SVC to the resampled training data

SVC()

In [ ]:
test_processed=preprocessor.transform(test)  # Transform the test data using the preprocessor

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

In [ ]:
x_test=test_processed[:,:-1]  # Extract the features (all columns except the last one) from the processed data
y_test=test_processed[:,-1]   # Extract the target variable (last column) from the processed data

In [ ]:
y_test

array([0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 1., 1., 0.,
       1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1.,
       0., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 1.,
       1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1.,
       1., 0., 1., 0.])

In [ ]:
# Getting predictions from model
y_pred=svclassifier.predict(x_test)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred))

[[ 1 34]
 [ 1 87]]

In [ ]:
print(accuracy_score(y_test,y_pred))

0.7154471544715447

In [ ]:
Hyper Parameter Tuning

SyntaxError: invalid syntax (3408100756.py, line 1)

In [ ]:
from itertools import product  # Importing the product function from itertools module

param_grid_linear = {           #  Define Parameter grid for linear kernel SVM
    'C': [0.1, 5, 10,50,60,70],
    'kernel': ['linear'],
    'gamma': ['scale', 'auto']
}
param_grid_rbf = {              # Define Parameter grid for Radial Basic Function-RBF
    'C': [0.1, 5, 10,50,60,70],
    'kernel': ['rbf'],
    'gamma': ['scale', 'auto']
}
param_grid_poly = {             # Define Parameters grid for Polynomial kernel
    'C': [0.1, 5, 10,50,60,70],
    'kernel': ['poly'],
    'gamma': ['scale', 'auto'],
    'degree': [2, 3, 4]
}

In [ ]:
param_grid1=[param_grid_linear,param_grid_rbf,param_grid_poly]

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

# Assigning SVC model into variables
model=SVC()
grid = RandomizedSearchCV(model,param_distributions=param_grid1, refit = True, verbose = 1,scoring='f1',cv=3)

# fitting the model for grid search
grid.fit(x_train_smote,y_train_smote)

Fitting 3 folds for each of 10 candidates, totalling 30 fits

RandomizedSearchCV(cv=3, estimator=SVC(),
                   param_distributions=[{'C': [0.1, 5, 10, 50, 60, 70],
                                         'gamma': ['scale', 'auto'],
                                         'kernel': ['linear']},
                                        {'C': [0.1, 5, 10, 50, 60, 70],
                                         'gamma': ['scale', 'auto'],
                                         'kernel': ['rbf']},
                                        {'C': [0.1, 5, 10, 50, 60, 70],
                                         'degree': [2, 3, 4],
                                         'gamma': ['scale', 'auto'],
                                         'kernel': ['poly']}],
                   scoring='f1', verbose=1)

In [ ]:
print(grid.best_params_)

{'kernel': 'rbf', 'gamma': 'scale', 'C': 60}

In [ ]:
svclassifier = SVC(C=60, gamma='scale',kernel='rbf' ) ## base model with default parameters
svclassifier.fit(x_train_smote,y_train_smote)

SVC(C=60)

In [ ]:
y_hat=grid.predict(x_test)

In [ ]:
print(classification_report(y_test,y_hat))

              precision    recall  f1-score   support

         0.0       0.81      0.63      0.71        35
         1.0       0.86      0.94      0.90        88

    accuracy                           0.85       123
   macro avg       0.84      0.79      0.81       123
weighted avg       0.85      0.85      0.85       123

In [ ]:
svclassifier.predict([[1.01,1.03,0.34,0.56,0.78,0.89,0.34,0.56,0.23,0.89,1.34,0.98,1.67,0.98,0.76]])

array([1.])

In [ ]:
with open("svmodel.pkl","wb") as f:
  pickle.dump(svclassifier,f)